apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: archetypev2
  labels:
    app: archetype
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: archetype
      version: v2
  template:
    metadata:
      labels:
        app: archetype
        version: v2
    spec:
      containers:
      - name: flask
        image: duffney/archetype:v2
