apiVersion: v1
kind: ReplicationController
metadata:
  name: archetype-v1
spec:
  replicas: 3
  template:
    metadata:
      name: archetype
      labels:
        app: archetype
    spec:
      containers:
      - image: duffney/archetype:v1
        name: flask
---
apiVersion: v1
kind: Service
metadata:
  name: archetype
spec:
  type: LoadBalancer
  selector:
    app: archetype
  ports:
  - port: 81
    targetPort: 80
